checks:
  addAllBuiltIn: true
  exclude:
    - "pdb-max-unavailable"
    - "env-var-secret"
    - "dangling-ingress"
    - "dangling-networkpolicy"
    - "wildcard-in-rules"
    - "access-to-create-pods"
    - "access-to-secrets"
    - "unset-cpu-requirements"
    - "unset-memory-requirements"
    - "use-namespace"
    - "no-liveness-probe"
    - "dnsconfig-options"
    - "no-node-affinity"
    - "no-readiness-probe"
    - "no-rolling-update-strategy"
    - "non-isolated-pod"
    - "required-annotation-email"
    - "required-label-owner"
    - "minimum-three-replicas"
    - "no-node-affinity"
    - "no-readiness-probe"
    - "read-secret-from-env-var"
    - "default-service-account"
    - "latest-tag"
    - "no-read-only-root-fs"
    - "run-as-non-root"
    - "writable-host-mount"
    - "privileged-container"
    - "drop-net-raw-capability"
    - "privilege-escalation-container"
    - "privileged-container"
 
