name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '23'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        native-image-job-reports: 'true'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Check Code Formatting
      run: ./gradlew spotlessCheck

    - name: Run Tests
      run: ./gradlew test

    - name: Build Native Image
      run: |
        ./gradlew build -Dquarkus.native.enabled=true -Dquarkus.package.jar.enabled=false -Dquarkus.native.additional-build-args='--emit build-report'
      env:
        GRAALVM_HOME: ${{ env.JAVA_HOME }}

    - name: Run native integration tests
      run: ./gradlew testNative
      env:
        GRAALVM_HOME: ${{ env.JAVA_HOME }}

    - name: Run integration tests
      run: ./gradlew quarkusIntTest
      env:
        GRAALVM_HOME: ${{ env.JAVA_HOME }}

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/reports/tests/

    - name: Upload Native Image Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: native-image-reports
        path: |
          build/**/*build-report.html
          build/**/*build-output-stats.json
          build/**/*build-artifacts.json

    - name: Cleanup Gradle Cache
      # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
      # Restoring these files from a GitHub Actions cache might cause problems for future builds.
      run: |
        rm -f ~/.gradle/caches/modules-2/modules-2.lock
        rm -f ~/.gradle/caches/modules-2/gc.properties 