name: Daily OWASP Dependency Check

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:      # Allows manual trigger

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Run dependency check
      id: dependency-check
      continue-on-error: true  # Allow the workflow to continue even if check fails
      run: |
        ./gradlew dependencyCheckAnalyze
        echo "check_exit_code=$?" >> $GITHUB_ENV
      
    - name: Upload dependency check report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: build/reports/dependency-check-report.html
        retention-days: 7
        
    - name: Upload SARIF report
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: build/reports/dependency-check-report.sarif

    - name: Check for vulnerabilities
      if: env.check_exit_code != '0'
      run: |
        echo "::error::High severity vulnerabilities found! Check the dependency report for details."
        exit 1